<?php

/**
 * Implements hook_menu().
 */
function country_page_menu() {
  $items['country/%country'] = array(
    'title callback' => 'countries_page_title',
    'title arguments' => array(1),
    'description' => 'View a country.',
    'page callback' => 'country_page_view',
    'page arguments' => array(1),
    'access callback' => 'country_page_view_access',
    'access arguments' => array(1),
  );
  return $items;
}


/**
 * Menu callback to view a country.
 */
function country_page_view($country) {
  return entity_view('country', array($country->iso2 => $country), 'full', NULL, TRUE);
}

/**
 * Implements hook_permission().
 */
function country_page_permission() {
  return array(
    'view country pages' =>  array(
      'title' => t('View country pages'),
      'description' => t('Lets users view non-administrative country pages.'),
    ),
  );
}

/**
 * Menu access callback.
 *
 * @param object $country
 * @return boolean
 */
function country_page_view_access($country) {
  if ($country->enabled || user_access('administer site configuration')) {
    return user_access('view country pages');
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function countryview_field_formatter_info() {
  return array(
    'countryview_link' => array(
      'label' => t('Link to country page'),
      'field types' => array('country'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function countryview_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'countryview_link':
      foreach($items as $delta => $item) {
        $element[$delta] = array('#markup' => l($item['country']->name, 'country/' . $item['iso2']));
      }
  }

  return $element;
}
